### ISSUE TITLE
connection refused

### ISSUE THREAD

**Issue by dimarapis** [richardbunker/hero9-webcam-for-linux#2]
Thanks for working on that and sharing. I am trying to connect to the gopro but I can't. On the browser the link gives back an error (unable to connect) and using telnet to connect to the gopro gives me "telnet: Unable to connect to remote host: Connection refused".

The gopro is on gopro connect mode. Any ideas? Thanks!

**Comment by richardbunker** [comment]
Sounds like you might not be targeting the gopro's correct IP address. Try a few other IPs on the network.

**Comment by moschmdt** [comment]
I have the same problem. I did check that the IP is correct...
